"""empty message

Revision ID: 87ee31881b8f
Revises: d0421f74a886
Create Date: 2023-10-07 17:50:07.339287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ee31881b8f'
down_revision = 'd0421f74a886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
