"""empty message

Revision ID: cb75bacfd77c
Revises: b2ee85f45471
Create Date: 2023-10-14 11:50:31.107579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb75bacfd77c'
down_revision = 'b2ee85f45471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('mobile', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('xyz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xyz',

    )
    op.drop_table('user_model')
    # ### end Alembic commands ###
